apiVersion: apps/v1
kind: Deployment
metadata:
  name: softwarewala
spec:
  replicas: 3
  selector:
    matchLabels:
      app: softwarewala
  template:
    metadata:
      labels:
        app: softwarewala
    spec:
      containers:
      - name: softwarewala-container
        image: your-image-name:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      imagePullSecrets:
      - name: your-image-pull-secret
