[flywaydb]
edition = "community"
locations = ["filesystem:./db-migrations/sql"]
driver = "org.postgresql.Driver"
url = "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require"
user = "${DB_USER}"
password = "${DB_PASSWORD}"
baselineVersion = "0"
baselineDescription = "Initial baseline"
undoSqlMigrationPrefix = "U"
sqlMigrationPrefix = "V"
sqlMigrationSeparator = "__"
sqlMigrationSuffixes = [".sql"]
validateOnMigrate = true
cleanDisabled = true
outOfOrder = false
